# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calibration.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calibration(object):
    def setupUi(self, Calibration):
        Calibration.setObjectName("Calibration")
        Calibration.resize(778, 610)
        self.gridLayout = QtWidgets.QGridLayout(Calibration)
        self.gridLayout.setObjectName("gridLayout")
        self.txComment = QtWidgets.QTextEdit(Calibration)
        self.txComment.setObjectName("txComment")
        self.gridLayout.addWidget(self.txComment, 10, 0, 1, 4)
        self.lbGeneratorCalLevel = QtWidgets.QLabel(Calibration)
        self.lbGeneratorCalLevel.setText("")
        self.lbGeneratorCalLevel.setObjectName("lbGeneratorCalLevel")
        self.gridLayout.addWidget(self.lbGeneratorCalLevel, 5, 3, 1, 1)
        self.pbCancel = QtWidgets.QPushButton(Calibration)
        self.pbCancel.setObjectName("pbCancel")
        self.gridLayout.addWidget(self.pbCancel, 11, 5, 1, 1)
        self.pbCorrectCal = QtWidgets.QPushButton(Calibration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCorrectCal.sizePolicy().hasHeightForWidth())
        self.pbCorrectCal.setSizePolicy(sizePolicy)
        self.pbCorrectCal.setObjectName("pbCorrectCal")
        self.gridLayout.addWidget(self.pbCorrectCal, 6, 5, 1, 1)
        self.lbGeneratorName = QtWidgets.QLabel(Calibration)
        self.lbGeneratorName.setObjectName("lbGeneratorName")
        self.gridLayout.addWidget(self.lbGeneratorName, 5, 1, 1, 1)
        self.lbLevelColumns = QtWidgets.QLabel(Calibration)
        self.lbLevelColumns.setAlignment(QtCore.Qt.AlignCenter)
        self.lbLevelColumns.setObjectName("lbLevelColumns")
        self.gridLayout.addWidget(self.lbLevelColumns, 3, 2, 1, 1)
        self.lbCalibrationColumn = QtWidgets.QLabel(Calibration)
        self.lbCalibrationColumn.setObjectName("lbCalibrationColumn")
        self.gridLayout.addWidget(self.lbCalibrationColumn, 4, 3, 1, 1)
        self.lbPlayerName = QtWidgets.QLabel(Calibration)
        self.lbPlayerName.setObjectName("lbPlayerName")
        self.gridLayout.addWidget(self.lbPlayerName, 6, 1, 1, 1)
        self.lbPlayerNameLabel = QtWidgets.QLabel(Calibration)
        self.lbPlayerNameLabel.setObjectName("lbPlayerNameLabel")
        self.gridLayout.addWidget(self.lbPlayerNameLabel, 6, 0, 1, 1)
        self.lePlayerLevel = QtWidgets.QLineEdit(Calibration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lePlayerLevel.sizePolicy().hasHeightForWidth())
        self.lePlayerLevel.setSizePolicy(sizePolicy)
        self.lePlayerLevel.setMinimumSize(QtCore.QSize(64, 0))
        self.lePlayerLevel.setObjectName("lePlayerLevel")
        self.gridLayout.addWidget(self.lePlayerLevel, 6, 2, 1, 1)
        self.lbPlayerCalLevel = QtWidgets.QLabel(Calibration)
        self.lbPlayerCalLevel.setMinimumSize(QtCore.QSize(64, 0))
        self.lbPlayerCalLevel.setText("")
        self.lbPlayerCalLevel.setObjectName("lbPlayerCalLevel")
        self.gridLayout.addWidget(self.lbPlayerCalLevel, 6, 3, 1, 1)
        self.lbOutputColumn = QtWidgets.QLabel(Calibration)
        self.lbOutputColumn.setObjectName("lbOutputColumn")
        self.gridLayout.addWidget(self.lbOutputColumn, 4, 2, 1, 1)
        self.lbFrameWorkCalLevel = QtWidgets.QLabel(Calibration)
        self.lbFrameWorkCalLevel.setMinimumSize(QtCore.QSize(64, 0))
        self.lbFrameWorkCalLevel.setText("")
        self.lbFrameWorkCalLevel.setObjectName("lbFrameWorkCalLevel")
        self.gridLayout.addWidget(self.lbFrameWorkCalLevel, 9, 3, 1, 1)
        self.lbGeneratorLevel = QtWidgets.QLabel(Calibration)
        self.lbGeneratorLevel.setMinimumSize(QtCore.QSize(64, 0))
        self.lbGeneratorLevel.setText("")
        self.lbGeneratorLevel.setObjectName("lbGeneratorLevel")
        self.gridLayout.addWidget(self.lbGeneratorLevel, 5, 2, 1, 1)
        self.leOutputLevel = QtWidgets.QLineEdit(Calibration)
        self.leOutputLevel.setMinimumSize(QtCore.QSize(64, 0))
        self.leOutputLevel.setObjectName("leOutputLevel")
        self.gridLayout.addWidget(self.leOutputLevel, 7, 2, 1, 1)
        self.lbFrameWorkCalLevelLabel = QtWidgets.QLabel(Calibration)
        self.lbFrameWorkCalLevelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lbFrameWorkCalLevelLabel.setObjectName("lbFrameWorkCalLevelLabel")
        self.gridLayout.addWidget(self.lbFrameWorkCalLevelLabel, 9, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        self.pbOK = QtWidgets.QPushButton(Calibration)
        self.pbOK.setObjectName("pbOK")
        self.gridLayout.addWidget(self.pbOK, 11, 4, 1, 1)
        self.lbGeneratorNameLabel = QtWidgets.QLabel(Calibration)
        self.lbGeneratorNameLabel.setObjectName("lbGeneratorNameLabel")
        self.gridLayout.addWidget(self.lbGeneratorNameLabel, 5, 0, 1, 1)
        self.lbOutputLevel = QtWidgets.QLabel(Calibration)
        self.lbOutputLevel.setObjectName("lbOutputLevel")
        self.gridLayout.addWidget(self.lbOutputLevel, 7, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.pbPlay = QtWidgets.QPushButton(Calibration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbPlay.sizePolicy().hasHeightForWidth())
        self.pbPlay.setSizePolicy(sizePolicy)
        self.pbPlay.setMinimumSize(QtCore.QSize(0, 64))
        self.pbPlay.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pbPlay.setCheckable(False)
        self.pbPlay.setObjectName("pbPlay")
        self.gridLayout.addWidget(self.pbPlay, 1, 1, 1, 4)

        self.retranslateUi(Calibration)
        QtCore.QMetaObject.connectSlotsByName(Calibration)

    def retranslateUi(self, Calibration):
        _translate = QtCore.QCoreApplication.translate
        Calibration.setWindowTitle(_translate("Calibration", "Dialog"))
        self.pbCancel.setText(_translate("Calibration", "Cancel"))
        self.pbCorrectCal.setText(_translate("Calibration", "Calibrate"))
        self.lbGeneratorName.setText(_translate("Calibration", "Name of generator"))
        self.lbLevelColumns.setText(_translate("Calibration", "Level"))
        self.lbCalibrationColumn.setText(_translate("Calibration", "Calibration"))
        self.lbPlayerName.setText(_translate("Calibration", "Name of player"))
        self.lbPlayerNameLabel.setText(_translate("Calibration", "Player: "))
        self.lbOutputColumn.setText(_translate("Calibration", "Output"))
        self.lbFrameWorkCalLevelLabel.setText(_translate("Calibration", "Calibration Level:\n"
"(FrameWork)"))
        self.pbOK.setText(_translate("Calibration", "OK"))
        self.lbGeneratorNameLabel.setText(_translate("Calibration", "Generator:"))
        self.lbOutputLevel.setText(_translate("Calibration", "Output:"))
        self.pbPlay.setText(_translate("Calibration", "Play Audio"))
