# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CICoachLabMainWindowGui2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1187, 1061)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setObjectName("formLayout")
        self.tabTrainerMode = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabTrainerMode.sizePolicy().hasHeightForWidth())
        self.tabTrainerMode.setSizePolicy(sizePolicy)
        self.tabTrainerMode.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tabTrainerMode.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabTrainerMode.setElideMode(QtCore.Qt.ElideNone)
        self.tabTrainerMode.setUsesScrollButtons(False)
        self.tabTrainerMode.setObjectName("tabTrainerMode")
        self.tabSingleRun = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSingleRun.sizePolicy().hasHeightForWidth())
        self.tabSingleRun.setSizePolicy(sizePolicy)
        self.tabSingleRun.setObjectName("tabSingleRun")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabSingleRun)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gbModules = QtWidgets.QGroupBox(self.tabSingleRun)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.gbModules.sizePolicy().hasHeightForWidth())
        self.gbModules.setSizePolicy(sizePolicy)
        self.gbModules.setMinimumSize(QtCore.QSize(0, 300))
        self.gbModules.setMaximumSize(QtCore.QSize(400, 600))
        self.gbModules.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.gbModules.setObjectName("gbModules")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbModules)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.gbModules)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.labelExer = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelExer.sizePolicy().hasHeightForWidth())
        self.labelExer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelExer.setFont(font)
        self.labelExer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelExer.setObjectName("labelExer")
        self.verticalLayout_7.addWidget(self.labelExer)
        self.lwExerNameVal = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.lwExerNameVal.sizePolicy().hasHeightForWidth())
        self.lwExerNameVal.setSizePolicy(sizePolicy)
        self.lwExerNameVal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lwExerNameVal.setSizeIncrement(QtCore.QSize(3, 3))
        self.lwExerNameVal.setObjectName("lwExerNameVal")
        self.verticalLayout_7.addWidget(self.lwExerNameVal)
        self.lwExerSetVal = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.lwExerSetVal.sizePolicy().hasHeightForWidth())
        self.lwExerSetVal.setSizePolicy(sizePolicy)
        self.lwExerSetVal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lwExerSetVal.setObjectName("lwExerSetVal")
        self.verticalLayout_7.addWidget(self.lwExerSetVal)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gbSubModules = QtWidgets.QGroupBox(self.gbModules)
        self.gbSubModules.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbSubModules.sizePolicy().hasHeightForWidth())
        self.gbSubModules.setSizePolicy(sizePolicy)
        self.gbSubModules.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gbSubModules.setTitle("")
        self.gbSubModules.setObjectName("gbSubModules")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gbSubModules)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelGenerator = QtWidgets.QLabel(self.gbSubModules)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGenerator.sizePolicy().hasHeightForWidth())
        self.labelGenerator.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelGenerator.setFont(font)
        self.labelGenerator.setObjectName("labelGenerator")
        self.verticalLayout_4.addWidget(self.labelGenerator)
        self.labelGeneratorNameVal = QtWidgets.QLabel(self.gbSubModules)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGeneratorNameVal.sizePolicy().hasHeightForWidth())
        self.labelGeneratorNameVal.setSizePolicy(sizePolicy)
        self.labelGeneratorNameVal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelGeneratorNameVal.setText("")
        self.labelGeneratorNameVal.setObjectName("labelGeneratorNameVal")
        self.verticalLayout_4.addWidget(self.labelGeneratorNameVal)
        self.labelGeneratorSetVal = QtWidgets.QLabel(self.gbSubModules)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGeneratorSetVal.sizePolicy().hasHeightForWidth())
        self.labelGeneratorSetVal.setSizePolicy(sizePolicy)
        self.labelGeneratorSetVal.setText("")
        self.labelGeneratorSetVal.setObjectName("labelGeneratorSetVal")
        self.verticalLayout_4.addWidget(self.labelGeneratorSetVal)
        self.labelPreProc = QtWidgets.QLabel(self.gbSubModules)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPreProc.sizePolicy().hasHeightForWidth())
        self.labelPreProc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelPreProc.setFont(font)
        self.labelPreProc.setObjectName("labelPreProc")
        self.verticalLayout_4.addWidget(self.labelPreProc)
        self.labelPreProcNameVal = QtWidgets.QLabel(self.gbSubModules)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPreProcNameVal.sizePolicy().hasHeightForWidth())
        self.labelPreProcNameVal.setSizePolicy(sizePolicy)
        self.labelPreProcNameVal.setText("")
        self.labelPreProcNameVal.setObjectName("labelPreProcNameVal")
        self.verticalLayout_4.addWidget(self.labelPreProcNameVal)
        self.labelPreProcSetVal = QtWidgets.QLabel(self.gbSubModules)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPreProcSetVal.sizePolicy().hasHeightForWidth())
        self.labelPreProcSetVal.setSizePolicy(sizePolicy)
        self.labelPreProcSetVal.setText("")
        self.labelPreProcSetVal.setObjectName("labelPreProcSetVal")
        self.verticalLayout_4.addWidget(self.labelPreProcSetVal)
        self.labelPlayer = QtWidgets.QLabel(self.gbSubModules)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPlayer.sizePolicy().hasHeightForWidth())
        self.labelPlayer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelPlayer.setFont(font)
        self.labelPlayer.setObjectName("labelPlayer")
        self.verticalLayout_4.addWidget(self.labelPlayer)
        self.labelPlayerNameVal = QtWidgets.QLabel(self.gbSubModules)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPlayerNameVal.sizePolicy().hasHeightForWidth())
        self.labelPlayerNameVal.setSizePolicy(sizePolicy)
        self.labelPlayerNameVal.setText("")
        self.labelPlayerNameVal.setObjectName("labelPlayerNameVal")
        self.verticalLayout_4.addWidget(self.labelPlayerNameVal)
        self.labelPlayerSetVal = QtWidgets.QLabel(self.gbSubModules)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPlayerSetVal.sizePolicy().hasHeightForWidth())
        self.labelPlayerSetVal.setSizePolicy(sizePolicy)
        self.labelPlayerSetVal.setText("")
        self.labelPlayerSetVal.setObjectName("labelPlayerSetVal")
        self.verticalLayout_4.addWidget(self.labelPlayerSetVal)
        self.verticalLayout.addWidget(self.gbSubModules)
        self.verticalLayout_3.addWidget(self.gbModules)
        self.groupBox = QtWidgets.QGroupBox(self.tabSingleRun)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pbNewRun = QtWidgets.QPushButton(self.groupBox)
        self.pbNewRun.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbNewRun.sizePolicy().hasHeightForWidth())
        self.pbNewRun.setSizePolicy(sizePolicy)
        self.pbNewRun.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbNewRun.setFont(font)
        self.pbNewRun.setObjectName("pbNewRun")
        self.verticalLayout_5.addWidget(self.pbNewRun)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.gbResults = QtWidgets.QGroupBox(self.tabSingleRun)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbResults.sizePolicy().hasHeightForWidth())
        self.gbResults.setSizePolicy(sizePolicy)
        self.gbResults.setTitle("")
        self.gbResults.setAlignment(QtCore.Qt.AlignCenter)
        self.gbResults.setObjectName("gbResults")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gbResults)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lwRuns = QtWidgets.QListWidget(self.gbResults)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwRuns.sizePolicy().hasHeightForWidth())
        self.lwRuns.setSizePolicy(sizePolicy)
        self.lwRuns.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lwRuns.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lwRuns.setObjectName("lwRuns")
        self.verticalLayout_6.addWidget(self.lwRuns)
        self.pbShowResults = QtWidgets.QPushButton(self.gbResults)
        self.pbShowResults.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbShowResults.sizePolicy().hasHeightForWidth())
        self.pbShowResults.setSizePolicy(sizePolicy)
        self.pbShowResults.setObjectName("pbShowResults")
        self.verticalLayout_6.addWidget(self.pbShowResults)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.gbResults)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.tabTrainerMode.addTab(self.tabSingleRun, "")
        self.tabSetlists = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSetlists.sizePolicy().hasHeightForWidth())
        self.tabSetlists.setSizePolicy(sizePolicy)
        self.tabSetlists.setObjectName("tabSetlists")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tabSetlists)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setSpacing(50)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lwSetlistNameVal = QtWidgets.QListWidget(self.tabSetlists)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwSetlistNameVal.sizePolicy().hasHeightForWidth())
        self.lwSetlistNameVal.setSizePolicy(sizePolicy)
        self.lwSetlistNameVal.setMaximumSize(QtCore.QSize(16777215, 200))
        self.lwSetlistNameVal.setObjectName("lwSetlistNameVal")
        self.verticalLayout_2.addWidget(self.lwSetlistNameVal)
        self.pbRunSetlist = QtWidgets.QPushButton(self.tabSetlists)
        self.pbRunSetlist.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbRunSetlist.sizePolicy().hasHeightForWidth())
        self.pbRunSetlist.setSizePolicy(sizePolicy)
        self.pbRunSetlist.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pbRunSetlist.setObjectName("pbRunSetlist")
        self.verticalLayout_2.addWidget(self.pbRunSetlist)
        self.pbStoppSetlist = QtWidgets.QPushButton(self.tabSetlists)
        self.pbStoppSetlist.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbStoppSetlist.sizePolicy().hasHeightForWidth())
        self.pbStoppSetlist.setSizePolicy(sizePolicy)
        self.pbStoppSetlist.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pbStoppSetlist.setObjectName("pbStoppSetlist")
        self.verticalLayout_2.addWidget(self.pbStoppSetlist)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.lwSetlistContentVal = QtWidgets.QListWidget(self.tabSetlists)
        self.lwSetlistContentVal.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwSetlistContentVal.sizePolicy().hasHeightForWidth())
        self.lwSetlistContentVal.setSizePolicy(sizePolicy)
        self.lwSetlistContentVal.setMaximumSize(QtCore.QSize(16777215, 200))
        self.lwSetlistContentVal.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.lwSetlistContentVal.setObjectName("lwSetlistContentVal")
        self.verticalLayout_2.addWidget(self.lwSetlistContentVal)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.tabTrainerMode.addTab(self.tabSetlists, "")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tabTrainerMode)
        self.exerWidget = QtWidgets.QGroupBox(self.centralwidget)
        self.exerWidget.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.exerWidget.sizePolicy().hasHeightForWidth())
        self.exerWidget.setSizePolicy(sizePolicy)
        self.exerWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.exerWidget.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.exerWidget.setCheckable(False)
        self.exerWidget.setObjectName("exerWidget")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.exerWidget)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1187, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setEnabled(True)
        self.menuFile.setObjectName("menuFile")
        self.menuExer = QtWidgets.QMenu(self.menubar)
        self.menuExer.setEnabled(True)
        self.menuExer.setObjectName("menuExer")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuGenerator = QtWidgets.QMenu(self.menubar)
        self.menuGenerator.setEnabled(True)
        self.menuGenerator.setObjectName("menuGenerator")
        self.menuPlayer = QtWidgets.QMenu(self.menubar)
        self.menuPlayer.setObjectName("menuPlayer")
        self.menuPreprocessor = QtWidgets.QMenu(self.menubar)
        self.menuPreprocessor.setObjectName("menuPreprocessor")
        self.menuSetlists = QtWidgets.QMenu(self.menubar)
        self.menuSetlists.setObjectName("menuSetlists")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuFileSave = QtWidgets.QAction(MainWindow)
        self.menuFileSave.setObjectName("menuFileSave")
        self.menuHelpAbout = QtWidgets.QAction(MainWindow)
        self.menuHelpAbout.setObjectName("menuHelpAbout")
        self.actionSettingsPlay = QtWidgets.QAction(MainWindow)
        self.actionSettingsPlay.setObjectName("actionSettingsPlay")
        self.actionSettingsGen = QtWidgets.QAction(MainWindow)
        self.actionSettingsGen.setObjectName("actionSettingsGen")
        self.actionPresetsGen = QtWidgets.QAction(MainWindow)
        self.actionPresetsGen.setObjectName("actionPresetsGen")
        self.actionPresetsPlay = QtWidgets.QAction(MainWindow)
        self.actionPresetsPlay.setObjectName("actionPresetsPlay")
        self.actionSetup = QtWidgets.QAction(MainWindow)
        self.actionSetup.setObjectName("actionSetup")
        self.actionSettingsExp = QtWidgets.QAction(MainWindow)
        self.actionSettingsExp.setObjectName("actionSettingsExp")
        self.actionSettingsGen1 = QtWidgets.QAction(MainWindow)
        self.actionSettingsGen1.setObjectName("actionSettingsGen1")
        self.actionSettingsPlay1 = QtWidgets.QAction(MainWindow)
        self.actionSettingsPlay1.setObjectName("actionSettingsPlay1")
        self.menuFileLoad = QtWidgets.QAction(MainWindow)
        self.menuFileLoad.setObjectName("menuFileLoad")
        self.menuXlsxExport = QtWidgets.QAction(MainWindow)
        self.menuXlsxExport.setObjectName("menuXlsxExport")
        self.menuFileUserData = QtWidgets.QAction(MainWindow)
        self.menuFileUserData.setObjectName("menuFileUserData")
        self.menuFileAppend = QtWidgets.QAction(MainWindow)
        self.menuFileAppend.setObjectName("menuFileAppend")
        self.menuFile.addAction(self.menuFileSave)
        self.menuFile.addAction(self.menuFileLoad)
        self.menuFile.addAction(self.menuFileAppend)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuXlsxExport)
        self.menuFile.addAction(self.menuFileUserData)
        self.menuFile.addSeparator()
        self.menuHelp.addAction(self.menuHelpAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuExer.menuAction())
        self.menubar.addAction(self.menuGenerator.menuAction())
        self.menubar.addAction(self.menuPreprocessor.menuAction())
        self.menubar.addAction(self.menuPlayer.menuAction())
        self.menubar.addAction(self.menuSetlists.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabTrainerMode.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CICoach Lab"))
        self.gbModules.setTitle(_translate("MainWindow", "Settings"))
        self.labelExer.setText(_translate("MainWindow", "Exercise:"))
        self.labelGenerator.setText(_translate("MainWindow", "Generator:"))
        self.labelPreProc.setText(_translate("MainWindow", "Preprocessor:"))
        self.labelPlayer.setText(_translate("MainWindow", "Player:"))
        self.pbNewRun.setText(_translate("MainWindow", "Start\n"
"new\n"
"exercise"))
        self.pbShowResults.setText(_translate("MainWindow", "Show results"))
        self.tabTrainerMode.setTabText(self.tabTrainerMode.indexOf(self.tabSingleRun), _translate("MainWindow", "Single Exercise"))
        self.pbRunSetlist.setText(_translate("MainWindow", "Start\n"
"set-list"))
        self.pbStoppSetlist.setText(_translate("MainWindow", "stopp\n"
"set-list"))
        self.tabTrainerMode.setTabText(self.tabTrainerMode.indexOf(self.tabSetlists), _translate("MainWindow", "Set-List"))
        self.exerWidget.setTitle(_translate("MainWindow", "Exercise"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuExer.setTitle(_translate("MainWindow", "E&xcercise"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuGenerator.setTitle(_translate("MainWindow", "Ge&nerator"))
        self.menuPlayer.setTitle(_translate("MainWindow", "Pla&yer"))
        self.menuPreprocessor.setTitle(_translate("MainWindow", "Prepro&cessor"))
        self.menuSetlists.setTitle(_translate("MainWindow", "Setlist"))
        self.menuFileSave.setText(_translate("MainWindow", "&Saving results"))
        self.menuHelpAbout.setText(_translate("MainWindow", "About"))
        self.actionSettingsPlay.setText(_translate("MainWindow", "Settings"))
        self.actionSettingsGen.setText(_translate("MainWindow", "Settings"))
        self.actionPresetsGen.setText(_translate("MainWindow", "Presets"))
        self.actionPresetsPlay.setText(_translate("MainWindow", "Presets"))
        self.actionSetup.setText(_translate("MainWindow", "Setup"))
        self.actionSettingsExp.setText(_translate("MainWindow", "&Settings"))
        self.actionSettingsGen1.setText(_translate("MainWindow", "&Settings"))
        self.actionSettingsPlay1.setText(_translate("MainWindow", "&Settings"))
        self.menuFileLoad.setText(_translate("MainWindow", "Loading results"))
        self.menuXlsxExport.setText(_translate("MainWindow", "&Export results to cvs file"))
        self.menuFileUserData.setText(_translate("MainWindow", "User data"))
        self.menuFileAppend.setText(_translate("MainWindow", "Appending results"))
