# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(970, 851)
        self.gridLayout_4 = QtWidgets.QGridLayout(SettingsWindow)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.twSettings = QtWidgets.QTabWidget(SettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twSettings.sizePolicy().hasHeightForWidth())
        self.twSettings.setSizePolicy(sizePolicy)
        self.twSettings.setMinimumSize(QtCore.QSize(1, 1))
        self.twSettings.setObjectName("twSettings")
        self.twExercise = QtWidgets.QWidget()
        self.twExercise.setObjectName("twExercise")
        self.glTabExer = QtWidgets.QGridLayout(self.twExercise)
        self.glTabExer.setObjectName("glTabExer")
        self.cbExerciseName = QtWidgets.QComboBox(self.twExercise)
        self.cbExerciseName.setEnabled(True)
        self.cbExerciseName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cbExerciseName.setFont(font)
        self.cbExerciseName.setEditable(True)
        self.cbExerciseName.setCurrentText("")
        self.cbExerciseName.setObjectName("cbExerciseName")
        self.glTabExer.addWidget(self.cbExerciseName, 1, 2, 1, 2)
        self.gbSubModules = QtWidgets.QGroupBox(self.twExercise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gbSubModules.sizePolicy().hasHeightForWidth())
        self.gbSubModules.setSizePolicy(sizePolicy)
        self.gbSubModules.setTitle("")
        self.gbSubModules.setObjectName("gbSubModules")
        self.vlSubModules = QtWidgets.QVBoxLayout(self.gbSubModules)
        self.vlSubModules.setObjectName("vlSubModules")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbExerciseSyncToExer = QtWidgets.QPushButton(self.gbSubModules)
        self.pbExerciseSyncToExer.setObjectName("pbExerciseSyncToExer")
        self.horizontalLayout.addWidget(self.pbExerciseSyncToExer)
        self.pbExerciseSyncFromExer = QtWidgets.QPushButton(self.gbSubModules)
        self.pbExerciseSyncFromExer.setObjectName("pbExerciseSyncFromExer")
        self.horizontalLayout.addWidget(self.pbExerciseSyncFromExer)
        self.vlSubModules.addLayout(self.horizontalLayout)
        self.glTabExer.addWidget(self.gbSubModules, 3, 3, 1, 1)
        self.gbExerciseSettings = QtWidgets.QGroupBox(self.twExercise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.gbExerciseSettings.sizePolicy().hasHeightForWidth())
        self.gbExerciseSettings.setSizePolicy(sizePolicy)
        self.gbExerciseSettings.setObjectName("gbExerciseSettings")
        self.glTabExer.addWidget(self.gbExerciseSettings, 4, 2, 1, 2)
        self.gbExerciseMain = QtWidgets.QGroupBox(self.twExercise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gbExerciseMain.sizePolicy().hasHeightForWidth())
        self.gbExerciseMain.setSizePolicy(sizePolicy)
        self.gbExerciseMain.setTitle("")
        self.gbExerciseMain.setObjectName("gbExerciseMain")
        self.vlExerMain = QtWidgets.QVBoxLayout(self.gbExerciseMain)
        self.vlExerMain.setObjectName("vlExerMain")
        self.cbExerciseSettingsName = QtWidgets.QComboBox(self.gbExerciseMain)
        self.cbExerciseSettingsName.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.cbExerciseSettingsName.setEditable(False)
        self.cbExerciseSettingsName.setObjectName("cbExerciseSettingsName")
        self.vlExerMain.addWidget(self.cbExerciseSettingsName)
        self.lbExerciseSettingsName = QtWidgets.QLabel(self.gbExerciseMain)
        self.lbExerciseSettingsName.setObjectName("lbExerciseSettingsName")
        self.vlExerMain.addWidget(self.lbExerciseSettingsName)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vlExerMain.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbExerciseNew = QtWidgets.QPushButton(self.gbExerciseMain)
        self.pbExerciseNew.setObjectName("pbExerciseNew")
        self.horizontalLayout_2.addWidget(self.pbExerciseNew)
        self.pbExerciseSaveAs = QtWidgets.QPushButton(self.gbExerciseMain)
        self.pbExerciseSaveAs.setObjectName("pbExerciseSaveAs")
        self.horizontalLayout_2.addWidget(self.pbExerciseSaveAs)
        self.pbExerciseSave = QtWidgets.QPushButton(self.gbExerciseMain)
        self.pbExerciseSave.setObjectName("pbExerciseSave")
        self.horizontalLayout_2.addWidget(self.pbExerciseSave)
        self.pbExerciseSaveAll = QtWidgets.QPushButton(self.gbExerciseMain)
        self.pbExerciseSaveAll.setObjectName("pbExerciseSaveAll")
        self.horizontalLayout_2.addWidget(self.pbExerciseSaveAll)
        self.vlExerMain.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vlExerMain.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pbExerciseReset = QtWidgets.QPushButton(self.gbExerciseMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbExerciseReset.sizePolicy().hasHeightForWidth())
        self.pbExerciseReset.setSizePolicy(sizePolicy)
        self.pbExerciseReset.setObjectName("pbExerciseReset")
        self.horizontalLayout_4.addWidget(self.pbExerciseReset)
        self.pbExerciseReload = QtWidgets.QPushButton(self.gbExerciseMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbExerciseReload.sizePolicy().hasHeightForWidth())
        self.pbExerciseReload.setSizePolicy(sizePolicy)
        self.pbExerciseReload.setObjectName("pbExerciseReload")
        self.horizontalLayout_4.addWidget(self.pbExerciseReload)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.vlExerMain.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vlExerMain.addItem(spacerItem4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbExerciseOK = QtWidgets.QPushButton(self.gbExerciseMain)
        self.pbExerciseOK.setObjectName("pbExerciseOK")
        self.horizontalLayout_3.addWidget(self.pbExerciseOK)
        self.pbExerciseCancel = QtWidgets.QPushButton(self.gbExerciseMain)
        self.pbExerciseCancel.setObjectName("pbExerciseCancel")
        self.horizontalLayout_3.addWidget(self.pbExerciseCancel)
        self.vlExerMain.addLayout(self.horizontalLayout_3)
        self.glTabExer.addWidget(self.gbExerciseMain, 3, 2, 1, 1)
        self.lbExerciseName = QtWidgets.QLabel(self.twExercise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbExerciseName.sizePolicy().hasHeightForWidth())
        self.lbExerciseName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbExerciseName.setFont(font)
        self.lbExerciseName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbExerciseName.setLineWidth(-3)
        self.lbExerciseName.setAlignment(QtCore.Qt.AlignCenter)
        self.lbExerciseName.setObjectName("lbExerciseName")
        self.glTabExer.addWidget(self.lbExerciseName, 2, 2, 1, 2)
        self.twSettings.addTab(self.twExercise, "")
        self.twGenerator = QtWidgets.QWidget()
        self.twGenerator.setObjectName("twGenerator")
        self.gridLayout = QtWidgets.QGridLayout(self.twGenerator)
        self.gridLayout.setObjectName("gridLayout")
        self.gbSubModules_2 = QtWidgets.QGroupBox(self.twGenerator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gbSubModules_2.sizePolicy().hasHeightForWidth())
        self.gbSubModules_2.setSizePolicy(sizePolicy)
        self.gbSubModules_2.setTitle("")
        self.gbSubModules_2.setObjectName("gbSubModules_2")
        self.vlSubModules_2 = QtWidgets.QVBoxLayout(self.gbSubModules_2)
        self.vlSubModules_2.setObjectName("vlSubModules_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pbGeneratorSyncToExer = QtWidgets.QPushButton(self.gbSubModules_2)
        self.pbGeneratorSyncToExer.setObjectName("pbGeneratorSyncToExer")
        self.horizontalLayout_11.addWidget(self.pbGeneratorSyncToExer)
        self.pbGeneratorSyncFromExer = QtWidgets.QPushButton(self.gbSubModules_2)
        self.pbGeneratorSyncFromExer.setObjectName("pbGeneratorSyncFromExer")
        self.horizontalLayout_11.addWidget(self.pbGeneratorSyncFromExer)
        self.vlSubModules_2.addLayout(self.horizontalLayout_11)
        self.gridLayout.addWidget(self.gbSubModules_2, 3, 1, 1, 1)
        self.gbGeneratorSettings = QtWidgets.QGroupBox(self.twGenerator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.gbGeneratorSettings.sizePolicy().hasHeightForWidth())
        self.gbGeneratorSettings.setSizePolicy(sizePolicy)
        self.gbGeneratorSettings.setObjectName("gbGeneratorSettings")
        self.gridLayout.addWidget(self.gbGeneratorSettings, 4, 0, 1, 2)
        self.cbGeneratorName = QtWidgets.QComboBox(self.twGenerator)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cbGeneratorName.setFont(font)
        self.cbGeneratorName.setObjectName("cbGeneratorName")
        self.gridLayout.addWidget(self.cbGeneratorName, 1, 0, 1, 2)
        self.gbGeneratorMain = QtWidgets.QGroupBox(self.twGenerator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gbGeneratorMain.sizePolicy().hasHeightForWidth())
        self.gbGeneratorMain.setSizePolicy(sizePolicy)
        self.gbGeneratorMain.setTitle("")
        self.gbGeneratorMain.setObjectName("gbGeneratorMain")
        self.vlExerMain_3 = QtWidgets.QVBoxLayout(self.gbGeneratorMain)
        self.vlExerMain_3.setObjectName("vlExerMain_3")
        self.cbGeneratorSettingsName = QtWidgets.QComboBox(self.gbGeneratorMain)
        self.cbGeneratorSettingsName.setEditable(False)
        self.cbGeneratorSettingsName.setObjectName("cbGeneratorSettingsName")
        self.vlExerMain_3.addWidget(self.cbGeneratorSettingsName)
        self.lbGeneratorSettingsName = QtWidgets.QLabel(self.gbGeneratorMain)
        self.lbGeneratorSettingsName.setObjectName("lbGeneratorSettingsName")
        self.vlExerMain_3.addWidget(self.lbGeneratorSettingsName)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vlExerMain_3.addItem(spacerItem5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pbGeneratorNew = QtWidgets.QPushButton(self.gbGeneratorMain)
        self.pbGeneratorNew.setObjectName("pbGeneratorNew")
        self.horizontalLayout_8.addWidget(self.pbGeneratorNew)
        self.pbGeneratorSaveAs = QtWidgets.QPushButton(self.gbGeneratorMain)
        self.pbGeneratorSaveAs.setObjectName("pbGeneratorSaveAs")
        self.horizontalLayout_8.addWidget(self.pbGeneratorSaveAs)
        self.pbGeneratorSave = QtWidgets.QPushButton(self.gbGeneratorMain)
        self.pbGeneratorSave.setObjectName("pbGeneratorSave")
        self.horizontalLayout_8.addWidget(self.pbGeneratorSave)
        self.pbGeneratorSaveAll = QtWidgets.QPushButton(self.gbGeneratorMain)
        self.pbGeneratorSaveAll.setObjectName("pbGeneratorSaveAll")
        self.horizontalLayout_8.addWidget(self.pbGeneratorSaveAll)
        self.vlExerMain_3.addLayout(self.horizontalLayout_8)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vlExerMain_3.addItem(spacerItem6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.pbGeneratorReset = QtWidgets.QPushButton(self.gbGeneratorMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbGeneratorReset.sizePolicy().hasHeightForWidth())
        self.pbGeneratorReset.setSizePolicy(sizePolicy)
        self.pbGeneratorReset.setObjectName("pbGeneratorReset")
        self.horizontalLayout_9.addWidget(self.pbGeneratorReset)
        self.pbGeneratorReload = QtWidgets.QPushButton(self.gbGeneratorMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbGeneratorReload.sizePolicy().hasHeightForWidth())
        self.pbGeneratorReload.setSizePolicy(sizePolicy)
        self.pbGeneratorReload.setObjectName("pbGeneratorReload")
        self.horizontalLayout_9.addWidget(self.pbGeneratorReload)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.vlExerMain_3.addLayout(self.horizontalLayout_9)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vlExerMain_3.addItem(spacerItem9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pbGeneratorOK = QtWidgets.QPushButton(self.gbGeneratorMain)
        self.pbGeneratorOK.setObjectName("pbGeneratorOK")
        self.horizontalLayout_10.addWidget(self.pbGeneratorOK)
        self.pbGeneratorCancel = QtWidgets.QPushButton(self.gbGeneratorMain)
        self.pbGeneratorCancel.setObjectName("pbGeneratorCancel")
        self.horizontalLayout_10.addWidget(self.pbGeneratorCancel)
        self.vlExerMain_3.addLayout(self.horizontalLayout_10)
        self.gridLayout.addWidget(self.gbGeneratorMain, 3, 0, 1, 1)
        self.lbGeneratorName = QtWidgets.QLabel(self.twGenerator)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbGeneratorName.setFont(font)
        self.lbGeneratorName.setAlignment(QtCore.Qt.AlignCenter)
        self.lbGeneratorName.setObjectName("lbGeneratorName")
        self.gridLayout.addWidget(self.lbGeneratorName, 2, 0, 1, 2)
        self.twSettings.addTab(self.twGenerator, "")
        self.twPreprocessor = QtWidgets.QWidget()
        self.twPreprocessor.setObjectName("twPreprocessor")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.twPreprocessor)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cbPreprocessorName = QtWidgets.QComboBox(self.twPreprocessor)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cbPreprocessorName.setFont(font)
        self.cbPreprocessorName.setObjectName("cbPreprocessorName")
        self.gridLayout_2.addWidget(self.cbPreprocessorName, 0, 0, 1, 2)
        self.lbPreprocessorName = QtWidgets.QLabel(self.twPreprocessor)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbPreprocessorName.setFont(font)
        self.lbPreprocessorName.setAlignment(QtCore.Qt.AlignCenter)
        self.lbPreprocessorName.setObjectName("lbPreprocessorName")
        self.gridLayout_2.addWidget(self.lbPreprocessorName, 1, 0, 1, 2)
        self.gbPreprocessorMain = QtWidgets.QGroupBox(self.twPreprocessor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gbPreprocessorMain.sizePolicy().hasHeightForWidth())
        self.gbPreprocessorMain.setSizePolicy(sizePolicy)
        self.gbPreprocessorMain.setTitle("")
        self.gbPreprocessorMain.setObjectName("gbPreprocessorMain")
        self.vlExerMain_5 = QtWidgets.QVBoxLayout(self.gbPreprocessorMain)
        self.vlExerMain_5.setObjectName("vlExerMain_5")
        self.cbPreprocessorSettingsName = QtWidgets.QComboBox(self.gbPreprocessorMain)
        self.cbPreprocessorSettingsName.setEditable(False)
        self.cbPreprocessorSettingsName.setObjectName("cbPreprocessorSettingsName")
        self.vlExerMain_5.addWidget(self.cbPreprocessorSettingsName)
        self.lbPreprocessorSettingsName = QtWidgets.QLabel(self.gbPreprocessorMain)
        self.lbPreprocessorSettingsName.setObjectName("lbPreprocessorSettingsName")
        self.vlExerMain_5.addWidget(self.lbPreprocessorSettingsName)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vlExerMain_5.addItem(spacerItem10)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pbPreprocessorNew = QtWidgets.QPushButton(self.gbPreprocessorMain)
        self.pbPreprocessorNew.setObjectName("pbPreprocessorNew")
        self.horizontalLayout_16.addWidget(self.pbPreprocessorNew)
        self.pbPreprocessorSaveAs = QtWidgets.QPushButton(self.gbPreprocessorMain)
        self.pbPreprocessorSaveAs.setObjectName("pbPreprocessorSaveAs")
        self.horizontalLayout_16.addWidget(self.pbPreprocessorSaveAs)
        self.pbPreprocessorSave = QtWidgets.QPushButton(self.gbPreprocessorMain)
        self.pbPreprocessorSave.setObjectName("pbPreprocessorSave")
        self.horizontalLayout_16.addWidget(self.pbPreprocessorSave)
        self.pbPreprocessorSaveAll = QtWidgets.QPushButton(self.gbPreprocessorMain)
        self.pbPreprocessorSaveAll.setObjectName("pbPreprocessorSaveAll")
        self.horizontalLayout_16.addWidget(self.pbPreprocessorSaveAll)
        self.vlExerMain_5.addLayout(self.horizontalLayout_16)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vlExerMain_5.addItem(spacerItem11)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem12)
        self.pbPreprocessorReset = QtWidgets.QPushButton(self.gbPreprocessorMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbPreprocessorReset.sizePolicy().hasHeightForWidth())
        self.pbPreprocessorReset.setSizePolicy(sizePolicy)
        self.pbPreprocessorReset.setObjectName("pbPreprocessorReset")
        self.horizontalLayout_17.addWidget(self.pbPreprocessorReset)
        self.pbPreprocessorReload = QtWidgets.QPushButton(self.gbPreprocessorMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbPreprocessorReload.sizePolicy().hasHeightForWidth())
        self.pbPreprocessorReload.setSizePolicy(sizePolicy)
        self.pbPreprocessorReload.setObjectName("pbPreprocessorReload")
        self.horizontalLayout_17.addWidget(self.pbPreprocessorReload)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem13)
        self.vlExerMain_5.addLayout(self.horizontalLayout_17)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vlExerMain_5.addItem(spacerItem14)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pbPreprocessorOK = QtWidgets.QPushButton(self.gbPreprocessorMain)
        self.pbPreprocessorOK.setObjectName("pbPreprocessorOK")
        self.horizontalLayout_18.addWidget(self.pbPreprocessorOK)
        self.pbPreprocessorCancel = QtWidgets.QPushButton(self.gbPreprocessorMain)
        self.pbPreprocessorCancel.setObjectName("pbPreprocessorCancel")
        self.horizontalLayout_18.addWidget(self.pbPreprocessorCancel)
        self.vlExerMain_5.addLayout(self.horizontalLayout_18)
        self.gridLayout_2.addWidget(self.gbPreprocessorMain, 2, 0, 1, 1)
        self.gbSubModules_3 = QtWidgets.QGroupBox(self.twPreprocessor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gbSubModules_3.sizePolicy().hasHeightForWidth())
        self.gbSubModules_3.setSizePolicy(sizePolicy)
        self.gbSubModules_3.setTitle("")
        self.gbSubModules_3.setObjectName("gbSubModules_3")
        self.vlSubModules_4 = QtWidgets.QVBoxLayout(self.gbSubModules_3)
        self.vlSubModules_4.setObjectName("vlSubModules_4")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pbPreprocessorSyncToExer = QtWidgets.QPushButton(self.gbSubModules_3)
        self.pbPreprocessorSyncToExer.setObjectName("pbPreprocessorSyncToExer")
        self.horizontalLayout_19.addWidget(self.pbPreprocessorSyncToExer)
        self.pbPreprocessorSyncFromExer = QtWidgets.QPushButton(self.gbSubModules_3)
        self.pbPreprocessorSyncFromExer.setObjectName("pbPreprocessorSyncFromExer")
        self.horizontalLayout_19.addWidget(self.pbPreprocessorSyncFromExer)
        self.vlSubModules_4.addLayout(self.horizontalLayout_19)
        self.gridLayout_2.addWidget(self.gbSubModules_3, 2, 1, 1, 1)
        self.gbPreprocessorSettings = QtWidgets.QGroupBox(self.twPreprocessor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.gbPreprocessorSettings.sizePolicy().hasHeightForWidth())
        self.gbPreprocessorSettings.setSizePolicy(sizePolicy)
        self.gbPreprocessorSettings.setObjectName("gbPreprocessorSettings")
        self.gridLayout_2.addWidget(self.gbPreprocessorSettings, 3, 0, 1, 2)
        self.twSettings.addTab(self.twPreprocessor, "")
        self.twPlayer = QtWidgets.QWidget()
        self.twPlayer.setObjectName("twPlayer")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.twPlayer)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cbPlayerName = QtWidgets.QComboBox(self.twPlayer)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cbPlayerName.setFont(font)
        self.cbPlayerName.setObjectName("cbPlayerName")
        self.gridLayout_3.addWidget(self.cbPlayerName, 0, 0, 1, 2)
        self.lbPlayerName = QtWidgets.QLabel(self.twPlayer)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbPlayerName.setFont(font)
        self.lbPlayerName.setAlignment(QtCore.Qt.AlignCenter)
        self.lbPlayerName.setObjectName("lbPlayerName")
        self.gridLayout_3.addWidget(self.lbPlayerName, 1, 0, 1, 2)
        self.gbPlayerMain = QtWidgets.QGroupBox(self.twPlayer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gbPlayerMain.sizePolicy().hasHeightForWidth())
        self.gbPlayerMain.setSizePolicy(sizePolicy)
        self.gbPlayerMain.setTitle("")
        self.gbPlayerMain.setObjectName("gbPlayerMain")
        self.vlExerMain_6 = QtWidgets.QVBoxLayout(self.gbPlayerMain)
        self.vlExerMain_6.setObjectName("vlExerMain_6")
        self.cbPlayerSettingsName = QtWidgets.QComboBox(self.gbPlayerMain)
        self.cbPlayerSettingsName.setEditable(False)
        self.cbPlayerSettingsName.setObjectName("cbPlayerSettingsName")
        self.vlExerMain_6.addWidget(self.cbPlayerSettingsName)
        self.lbPlayerSettingsName = QtWidgets.QLabel(self.gbPlayerMain)
        self.lbPlayerSettingsName.setObjectName("lbPlayerSettingsName")
        self.vlExerMain_6.addWidget(self.lbPlayerSettingsName)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vlExerMain_6.addItem(spacerItem15)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pbPlayerNew = QtWidgets.QPushButton(self.gbPlayerMain)
        self.pbPlayerNew.setObjectName("pbPlayerNew")
        self.horizontalLayout_21.addWidget(self.pbPlayerNew)
        self.pbPlayerSaveAs = QtWidgets.QPushButton(self.gbPlayerMain)
        self.pbPlayerSaveAs.setObjectName("pbPlayerSaveAs")
        self.horizontalLayout_21.addWidget(self.pbPlayerSaveAs)
        self.pbPlayerSave = QtWidgets.QPushButton(self.gbPlayerMain)
        self.pbPlayerSave.setObjectName("pbPlayerSave")
        self.horizontalLayout_21.addWidget(self.pbPlayerSave)
        self.pbPlayerSaveAll = QtWidgets.QPushButton(self.gbPlayerMain)
        self.pbPlayerSaveAll.setObjectName("pbPlayerSaveAll")
        self.horizontalLayout_21.addWidget(self.pbPlayerSaveAll)
        self.vlExerMain_6.addLayout(self.horizontalLayout_21)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vlExerMain_6.addItem(spacerItem16)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem17)
        self.pbPlayerReset = QtWidgets.QPushButton(self.gbPlayerMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbPlayerReset.sizePolicy().hasHeightForWidth())
        self.pbPlayerReset.setSizePolicy(sizePolicy)
        self.pbPlayerReset.setObjectName("pbPlayerReset")
        self.horizontalLayout_22.addWidget(self.pbPlayerReset)
        self.pbPlayerReload = QtWidgets.QPushButton(self.gbPlayerMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbPlayerReload.sizePolicy().hasHeightForWidth())
        self.pbPlayerReload.setSizePolicy(sizePolicy)
        self.pbPlayerReload.setObjectName("pbPlayerReload")
        self.horizontalLayout_22.addWidget(self.pbPlayerReload)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem18)
        self.vlExerMain_6.addLayout(self.horizontalLayout_22)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vlExerMain_6.addItem(spacerItem19)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pbPlayerOK = QtWidgets.QPushButton(self.gbPlayerMain)
        self.pbPlayerOK.setObjectName("pbPlayerOK")
        self.horizontalLayout_23.addWidget(self.pbPlayerOK)
        self.pbPlayerCancel = QtWidgets.QPushButton(self.gbPlayerMain)
        self.pbPlayerCancel.setObjectName("pbPlayerCancel")
        self.horizontalLayout_23.addWidget(self.pbPlayerCancel)
        self.vlExerMain_6.addLayout(self.horizontalLayout_23)
        self.gridLayout_3.addWidget(self.gbPlayerMain, 2, 0, 1, 1)
        self.gbSubModules_4 = QtWidgets.QGroupBox(self.twPlayer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gbSubModules_4.sizePolicy().hasHeightForWidth())
        self.gbSubModules_4.setSizePolicy(sizePolicy)
        self.gbSubModules_4.setTitle("")
        self.gbSubModules_4.setObjectName("gbSubModules_4")
        self.vlSubModules_5 = QtWidgets.QVBoxLayout(self.gbSubModules_4)
        self.vlSubModules_5.setObjectName("vlSubModules_5")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.pbPlayerSyncToExer = QtWidgets.QPushButton(self.gbSubModules_4)
        self.pbPlayerSyncToExer.setObjectName("pbPlayerSyncToExer")
        self.horizontalLayout_20.addWidget(self.pbPlayerSyncToExer)
        self.pbPlayerSyncFromExer = QtWidgets.QPushButton(self.gbSubModules_4)
        self.pbPlayerSyncFromExer.setObjectName("pbPlayerSyncFromExer")
        self.horizontalLayout_20.addWidget(self.pbPlayerSyncFromExer)
        self.vlSubModules_5.addLayout(self.horizontalLayout_20)
        self.gridLayout_3.addWidget(self.gbSubModules_4, 2, 1, 1, 1)
        self.gbPlayerSettings = QtWidgets.QGroupBox(self.twPlayer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.gbPlayerSettings.sizePolicy().hasHeightForWidth())
        self.gbPlayerSettings.setSizePolicy(sizePolicy)
        self.gbPlayerSettings.setObjectName("gbPlayerSettings")
        self.gridLayout_3.addWidget(self.gbPlayerSettings, 3, 0, 1, 2)
        self.twSettings.addTab(self.twPlayer, "")
        self.gridLayout_4.addWidget(self.twSettings, 0, 0, 1, 1)

        self.retranslateUi(SettingsWindow)
        self.twSettings.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Settings"))
        self.pbExerciseSyncToExer.setToolTip(_translate("SettingsWindow", "Syncing chosen modules to settings tabs"))
        self.pbExerciseSyncToExer.setText(_translate("SettingsWindow", "Sync to"))
        self.pbExerciseSyncFromExer.setToolTip(_translate("SettingsWindow", "Syncing modules from settings tabs"))
        self.pbExerciseSyncFromExer.setText(_translate("SettingsWindow", "Sync from"))
        self.gbExerciseSettings.setTitle(_translate("SettingsWindow", "Settings"))
        self.lbExerciseSettingsName.setText(_translate("SettingsWindow", "TextLabel"))
        self.pbExerciseNew.setText(_translate("SettingsWindow", "New"))
        self.pbExerciseSaveAs.setToolTip(_translate("SettingsWindow", "Saving settings as selectable preset file"))
        self.pbExerciseSaveAs.setText(_translate("SettingsWindow", "Save as"))
        self.pbExerciseSave.setToolTip(_translate("SettingsWindow", "Saving settings as preset file"))
        self.pbExerciseSave.setText(_translate("SettingsWindow", "Save"))
        self.pbExerciseSaveAll.setToolTip(_translate("SettingsWindow", "Saving settings of all modules into a single settings file"))
        self.pbExerciseSaveAll.setText(_translate("SettingsWindow", "Save all"))
        self.pbExerciseReset.setText(_translate("SettingsWindow", "Reset"))
        self.pbExerciseReload.setText(_translate("SettingsWindow", "Reload"))
        self.pbExerciseOK.setToolTip(_translate("SettingsWindow", "Leaving Settings dialog and applying all settings"))
        self.pbExerciseOK.setText(_translate("SettingsWindow", "OK"))
        self.pbExerciseCancel.setToolTip(_translate("SettingsWindow", "Leaving Settings dialog and discarding all settings"))
        self.pbExerciseCancel.setText(_translate("SettingsWindow", "Cancel"))
        self.lbExerciseName.setText(_translate("SettingsWindow", "Exercise"))
        self.twSettings.setTabText(self.twSettings.indexOf(self.twExercise), _translate("SettingsWindow", "Exercise"))
        self.pbGeneratorSyncToExer.setToolTip(_translate("SettingsWindow", "Syncing chosen modules to settings tabs"))
        self.pbGeneratorSyncToExer.setText(_translate("SettingsWindow", "Sync to"))
        self.pbGeneratorSyncFromExer.setToolTip(_translate("SettingsWindow", "Syncing modules from settings tabs"))
        self.pbGeneratorSyncFromExer.setText(_translate("SettingsWindow", "Sync from"))
        self.gbGeneratorSettings.setTitle(_translate("SettingsWindow", "Settings"))
        self.lbGeneratorSettingsName.setText(_translate("SettingsWindow", "TextLabel"))
        self.pbGeneratorNew.setText(_translate("SettingsWindow", "New"))
        self.pbGeneratorSaveAs.setToolTip(_translate("SettingsWindow", "Saving settings as selectable preset file"))
        self.pbGeneratorSaveAs.setText(_translate("SettingsWindow", "Save as"))
        self.pbGeneratorSave.setToolTip(_translate("SettingsWindow", "Saving settings as preset file"))
        self.pbGeneratorSave.setText(_translate("SettingsWindow", "Save"))
        self.pbGeneratorSaveAll.setText(_translate("SettingsWindow", "Save All"))
        self.pbGeneratorReset.setText(_translate("SettingsWindow", "Reset"))
        self.pbGeneratorReload.setText(_translate("SettingsWindow", "Reload"))
        self.pbGeneratorOK.setToolTip(_translate("SettingsWindow", "Leaving Settings dialog and aplying all settings"))
        self.pbGeneratorOK.setText(_translate("SettingsWindow", "OK"))
        self.pbGeneratorCancel.setToolTip(_translate("SettingsWindow", "Leaving Settings dialog and discarding all settings"))
        self.pbGeneratorCancel.setText(_translate("SettingsWindow", "Cancel"))
        self.lbGeneratorName.setText(_translate("SettingsWindow", "Generator name"))
        self.twSettings.setTabText(self.twSettings.indexOf(self.twGenerator), _translate("SettingsWindow", "Generator"))
        self.lbPreprocessorName.setText(_translate("SettingsWindow", "Preprocessor name"))
        self.lbPreprocessorSettingsName.setText(_translate("SettingsWindow", "TextLabel"))
        self.pbPreprocessorNew.setText(_translate("SettingsWindow", "New"))
        self.pbPreprocessorSaveAs.setToolTip(_translate("SettingsWindow", "Saving settings as selectable preset file"))
        self.pbPreprocessorSaveAs.setText(_translate("SettingsWindow", "Save as"))
        self.pbPreprocessorSave.setToolTip(_translate("SettingsWindow", "Saving settings as preset file"))
        self.pbPreprocessorSave.setText(_translate("SettingsWindow", "Save"))
        self.pbPreprocessorSaveAll.setText(_translate("SettingsWindow", "Save All"))
        self.pbPreprocessorReset.setText(_translate("SettingsWindow", "Reset"))
        self.pbPreprocessorReload.setText(_translate("SettingsWindow", "Reload"))
        self.pbPreprocessorOK.setToolTip(_translate("SettingsWindow", "Leaving Settings dialog and aplying all settings"))
        self.pbPreprocessorOK.setText(_translate("SettingsWindow", "OK"))
        self.pbPreprocessorCancel.setToolTip(_translate("SettingsWindow", "Leaving Settings dialog and discarding all settings"))
        self.pbPreprocessorCancel.setText(_translate("SettingsWindow", "Cancel"))
        self.pbPreprocessorSyncToExer.setToolTip(_translate("SettingsWindow", "Syncing chosen modules to settings tabs"))
        self.pbPreprocessorSyncToExer.setText(_translate("SettingsWindow", "Sync to"))
        self.pbPreprocessorSyncFromExer.setToolTip(_translate("SettingsWindow", "Syncing modules from settings tabs"))
        self.pbPreprocessorSyncFromExer.setText(_translate("SettingsWindow", "Sync from"))
        self.gbPreprocessorSettings.setTitle(_translate("SettingsWindow", "Settings"))
        self.twSettings.setTabText(self.twSettings.indexOf(self.twPreprocessor), _translate("SettingsWindow", "Preprocessor"))
        self.lbPlayerName.setText(_translate("SettingsWindow", "Player name"))
        self.lbPlayerSettingsName.setText(_translate("SettingsWindow", "TextLabel"))
        self.pbPlayerNew.setText(_translate("SettingsWindow", "New"))
        self.pbPlayerSaveAs.setToolTip(_translate("SettingsWindow", "Saving settings as selectable preset file"))
        self.pbPlayerSaveAs.setText(_translate("SettingsWindow", "Save as"))
        self.pbPlayerSave.setToolTip(_translate("SettingsWindow", "Saving settings as preset file"))
        self.pbPlayerSave.setText(_translate("SettingsWindow", "Save"))
        self.pbPlayerSaveAll.setText(_translate("SettingsWindow", "Save All"))
        self.pbPlayerReset.setText(_translate("SettingsWindow", "Reset"))
        self.pbPlayerReload.setText(_translate("SettingsWindow", "Reload"))
        self.pbPlayerOK.setToolTip(_translate("SettingsWindow", "Leaving Settings dialog and aplying all settings"))
        self.pbPlayerOK.setText(_translate("SettingsWindow", "OK"))
        self.pbPlayerCancel.setToolTip(_translate("SettingsWindow", "Leaving Settings dialog and discarding all settings"))
        self.pbPlayerCancel.setText(_translate("SettingsWindow", "Cancel"))
        self.pbPlayerSyncToExer.setToolTip(_translate("SettingsWindow", "Syncing chosen modules to settings tabs"))
        self.pbPlayerSyncToExer.setText(_translate("SettingsWindow", "Sync to"))
        self.pbPlayerSyncFromExer.setToolTip(_translate("SettingsWindow", "Syncing modules from settings tabs"))
        self.pbPlayerSyncFromExer.setText(_translate("SettingsWindow", "Sync from"))
        self.gbPlayerSettings.setTitle(_translate("SettingsWindow", "Settings"))
        self.twSettings.setTabText(self.twSettings.indexOf(self.twPlayer), _translate("SettingsWindow", "Player"))
