# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserDataDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserDataDialog(object):
    def setupUi(self, UserDataDialog):
        UserDataDialog.setObjectName("UserDataDialog")
        UserDataDialog.resize(704, 780)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(UserDataDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.personalData = QtWidgets.QHBoxLayout()
        self.personalData.setObjectName("personalData")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lbLastname = QtWidgets.QLabel(UserDataDialog)
        self.lbLastname.setObjectName("lbLastname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbLastname)
        self.lastname = QtWidgets.QLineEdit(UserDataDialog)
        self.lastname.setObjectName("lastname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lastname)
        self.lbForname = QtWidgets.QLabel(UserDataDialog)
        self.lbForname.setObjectName("lbForname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbForname)
        self.forname = QtWidgets.QLineEdit(UserDataDialog)
        self.forname.setObjectName("forname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.forname)
        self.lbPatientID = QtWidgets.QLabel(UserDataDialog)
        self.lbPatientID.setToolTip("")
        self.lbPatientID.setStatusTip("")
        self.lbPatientID.setObjectName("lbPatientID")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbPatientID)
        self.patientID = QtWidgets.QLineEdit(UserDataDialog)
        self.patientID.setObjectName("patientID")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.patientID)
        self.lbGender = QtWidgets.QLabel(UserDataDialog)
        self.lbGender.setToolTip("")
        self.lbGender.setObjectName("lbGender")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbGender)
        self.gender = QtWidgets.QComboBox(UserDataDialog)
        self.gender.setObjectName("gender")
        self.gender.addItem("")
        self.gender.setItemText(0, "")
        self.gender.addItem("")
        self.gender.addItem("")
        self.gender.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.gender)
        self.lbBirthday = QtWidgets.QLabel(UserDataDialog)
        self.lbBirthday.setToolTip("")
        self.lbBirthday.setObjectName("lbBirthday")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbBirthday)
        self.birthday = QtWidgets.QDateEdit(UserDataDialog)
        self.birthday.setMaximumDate(QtCore.QDate(2020, 12, 31))
        self.birthday.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.birthday.setCalendarPopup(True)
        self.birthday.setDate(QtCore.QDate(1900, 1, 1))
        self.birthday.setObjectName("birthday")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.birthday)
        self.personalData.addLayout(self.formLayout)
        self.verticalLayout_2.addLayout(self.personalData)
        self.anamnese = QtWidgets.QHBoxLayout()
        self.anamnese.setObjectName("anamnese")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lbTinnitus = QtWidgets.QLabel(UserDataDialog)
        self.lbTinnitus.setObjectName("lbTinnitus")
        self.gridLayout.addWidget(self.lbTinnitus, 4, 0, 1, 1)
        self.lbVertigo = QtWidgets.QLabel(UserDataDialog)
        self.lbVertigo.setObjectName("lbVertigo")
        self.gridLayout.addWidget(self.lbVertigo, 5, 0, 1, 1)
        self.deafReason = QtWidgets.QHBoxLayout()
        self.deafReason.setObjectName("deafReason")
        self.left_deafReason = QtWidgets.QComboBox(UserDataDialog)
        self.left_deafReason.setObjectName("left_deafReason")
        self.left_deafReason.addItem("")
        self.left_deafReason.setItemText(0, "")
        self.left_deafReason.addItem("")
        self.left_deafReason.addItem("")
        self.left_deafReason.addItem("")
        self.left_deafReason.addItem("")
        self.left_deafReason.addItem("")
        self.left_deafReason.addItem("")
        self.deafReason.addWidget(self.left_deafReason)
        self.right_deafReason = QtWidgets.QComboBox(UserDataDialog)
        self.right_deafReason.setObjectName("right_deafReason")
        self.right_deafReason.addItem("")
        self.right_deafReason.setItemText(0, "")
        self.right_deafReason.addItem("")
        self.right_deafReason.addItem("")
        self.right_deafReason.addItem("")
        self.right_deafReason.addItem("")
        self.right_deafReason.addItem("")
        self.right_deafReason.addItem("")
        self.deafReason.addWidget(self.right_deafReason)
        self.gridLayout.addLayout(self.deafReason, 2, 1, 1, 1)
        self.lbDeafBeforeCI = QtWidgets.QLabel(UserDataDialog)
        self.lbDeafBeforeCI.setObjectName("lbDeafBeforeCI")
        self.gridLayout.addWidget(self.lbDeafBeforeCI, 1, 0, 1, 1)
        self.lbDeafeningProgress = QtWidgets.QLabel(UserDataDialog)
        self.lbDeafeningProgress.setObjectName("lbDeafeningProgress")
        self.gridLayout.addWidget(self.lbDeafeningProgress, 3, 0, 1, 1)
        self.lbDeafReason = QtWidgets.QLabel(UserDataDialog)
        self.lbDeafReason.setObjectName("lbDeafReason")
        self.gridLayout.addWidget(self.lbDeafReason, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_tinnitus = QtWidgets.QComboBox(UserDataDialog)
        self.left_tinnitus.setObjectName("left_tinnitus")
        self.left_tinnitus.addItem("")
        self.left_tinnitus.setItemText(0, "")
        self.left_tinnitus.addItem("")
        self.left_tinnitus.addItem("")
        self.horizontalLayout.addWidget(self.left_tinnitus)
        self.right_tinnitus = QtWidgets.QComboBox(UserDataDialog)
        self.right_tinnitus.setObjectName("right_tinnitus")
        self.right_tinnitus.addItem("")
        self.right_tinnitus.setItemText(0, "")
        self.right_tinnitus.addItem("")
        self.right_tinnitus.addItem("")
        self.horizontalLayout.addWidget(self.right_tinnitus)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        self.deafBeforeCI = QtWidgets.QHBoxLayout()
        self.deafBeforeCI.setObjectName("deafBeforeCI")
        self.left_deafBeforeCI = QtWidgets.QComboBox(UserDataDialog)
        self.left_deafBeforeCI.setObjectName("left_deafBeforeCI")
        self.left_deafBeforeCI.addItem("")
        self.left_deafBeforeCI.setItemText(0, "")
        self.left_deafBeforeCI.addItem("")
        self.left_deafBeforeCI.addItem("")
        self.left_deafBeforeCI.addItem("")
        self.left_deafBeforeCI.addItem("")
        self.left_deafBeforeCI.addItem("")
        self.left_deafBeforeCI.addItem("")
        self.deafBeforeCI.addWidget(self.left_deafBeforeCI)
        self.right_deafBeforeCI = QtWidgets.QComboBox(UserDataDialog)
        self.right_deafBeforeCI.setObjectName("right_deafBeforeCI")
        self.right_deafBeforeCI.addItem("")
        self.right_deafBeforeCI.setItemText(0, "")
        self.right_deafBeforeCI.addItem("")
        self.right_deafBeforeCI.addItem("")
        self.right_deafBeforeCI.addItem("")
        self.right_deafBeforeCI.addItem("")
        self.right_deafBeforeCI.addItem("")
        self.right_deafBeforeCI.addItem("")
        self.deafBeforeCI.addWidget(self.right_deafBeforeCI)
        self.gridLayout.addLayout(self.deafBeforeCI, 1, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.left_deafeningProgress = QtWidgets.QComboBox(UserDataDialog)
        self.left_deafeningProgress.setObjectName("left_deafeningProgress")
        self.left_deafeningProgress.addItem("")
        self.left_deafeningProgress.setItemText(0, "")
        self.left_deafeningProgress.addItem("")
        self.left_deafeningProgress.addItem("")
        self.horizontalLayout_10.addWidget(self.left_deafeningProgress)
        self.right_deafeningProgress = QtWidgets.QComboBox(UserDataDialog)
        self.right_deafeningProgress.setObjectName("right_deafeningProgress")
        self.right_deafeningProgress.addItem("")
        self.right_deafeningProgress.setItemText(0, "")
        self.right_deafeningProgress.addItem("")
        self.right_deafeningProgress.addItem("")
        self.horizontalLayout_10.addWidget(self.right_deafeningProgress)
        self.gridLayout.addLayout(self.horizontalLayout_10, 3, 1, 1, 1)
        self.vertigo = QtWidgets.QComboBox(UserDataDialog)
        self.vertigo.setObjectName("vertigo")
        self.vertigo.addItem("")
        self.vertigo.setItemText(0, "")
        self.vertigo.addItem("")
        self.vertigo.addItem("")
        self.gridLayout.addWidget(self.vertigo, 5, 1, 1, 1)
        self.treatment = QtWidgets.QHBoxLayout()
        self.treatment.setObjectName("treatment")
        self.left_treatment = QtWidgets.QComboBox(UserDataDialog)
        self.left_treatment.setObjectName("left_treatment")
        self.left_treatment.addItem("")
        self.left_treatment.setItemText(0, "")
        self.left_treatment.addItem("")
        self.left_treatment.addItem("")
        self.left_treatment.addItem("")
        self.left_treatment.addItem("")
        self.left_treatment.addItem("")
        self.treatment.addWidget(self.left_treatment)
        self.right_treatment = QtWidgets.QComboBox(UserDataDialog)
        self.right_treatment.setObjectName("right_treatment")
        self.right_treatment.addItem("")
        self.right_treatment.setItemText(0, "")
        self.right_treatment.addItem("")
        self.right_treatment.addItem("")
        self.right_treatment.addItem("")
        self.right_treatment.addItem("")
        self.right_treatment.addItem("")
        self.treatment.addWidget(self.right_treatment)
        self.gridLayout.addLayout(self.treatment, 0, 1, 1, 1)
        self.lbTreatment = QtWidgets.QLabel(UserDataDialog)
        self.lbTreatment.setObjectName("lbTreatment")
        self.gridLayout.addWidget(self.lbTreatment, 0, 0, 1, 1)
        self.anamnese.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.anamnese)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.subjectID = QtWidgets.QLineEdit(UserDataDialog)
        self.subjectID.setObjectName("subjectID")
        self.gridLayout_2.addWidget(self.subjectID, 1, 1, 1, 1)
        self.lbSubjectId = QtWidgets.QLabel(UserDataDialog)
        self.lbSubjectId.setToolTip("")
        self.lbSubjectId.setObjectName("lbSubjectId")
        self.gridLayout_2.addWidget(self.lbSubjectId, 1, 0, 1, 1)
        self.lbStudyCheck = QtWidgets.QLabel(UserDataDialog)
        self.lbStudyCheck.setToolTip("")
        self.lbStudyCheck.setObjectName("lbStudyCheck")
        self.gridLayout_2.addWidget(self.lbStudyCheck, 2, 0, 1, 1)
        self.studyCheck = QtWidgets.QCheckBox(UserDataDialog)
        self.studyCheck.setObjectName("studyCheck")
        self.gridLayout_2.addWidget(self.studyCheck, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        spacerItem = QtWidgets.QSpacerItem(17, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.difficultyGrade = QtWidgets.QHBoxLayout()
        self.difficultyGrade.setObjectName("difficultyGrade")
        self.lbDifficulty = QtWidgets.QLabel(UserDataDialog)
        self.lbDifficulty.setObjectName("lbDifficulty")
        self.difficultyGrade.addWidget(self.lbDifficulty)
        self.difficulty = QtWidgets.QComboBox(UserDataDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.difficulty.sizePolicy().hasHeightForWidth())
        self.difficulty.setSizePolicy(sizePolicy)
        self.difficulty.setObjectName("difficulty")
        self.difficulty.addItem("")
        self.difficulty.addItem("")
        self.difficulty.addItem("")
        self.difficulty.addItem("")
        self.difficulty.addItem("")
        self.difficultyGrade.addWidget(self.difficulty)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.difficultyGrade.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.difficultyGrade)
        self.lbComment = QtWidgets.QLabel(UserDataDialog)
        self.lbComment.setObjectName("lbComment")
        self.verticalLayout_2.addWidget(self.lbComment)
        self.comment = QtWidgets.QTextEdit(UserDataDialog)
        self.comment.setObjectName("comment")
        self.verticalLayout_2.addWidget(self.comment)
        self.buttons = QtWidgets.QHBoxLayout()
        self.buttons.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.buttons.setObjectName("buttons")
        self.pbClear = QtWidgets.QPushButton(UserDataDialog)
        self.pbClear.setObjectName("pbClear")
        self.buttons.addWidget(self.pbClear)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons.addItem(spacerItem2)
        self.pbSave = QtWidgets.QPushButton(UserDataDialog)
        self.pbSave.setObjectName("pbSave")
        self.buttons.addWidget(self.pbSave)
        self.pbCancel = QtWidgets.QPushButton(UserDataDialog)
        self.pbCancel.setObjectName("pbCancel")
        self.buttons.addWidget(self.pbCancel)
        self.verticalLayout_2.addLayout(self.buttons)

        self.retranslateUi(UserDataDialog)
        QtCore.QMetaObject.connectSlotsByName(UserDataDialog)
        UserDataDialog.setTabOrder(self.lastname, self.forname)
        UserDataDialog.setTabOrder(self.forname, self.patientID)
        UserDataDialog.setTabOrder(self.patientID, self.birthday)
        UserDataDialog.setTabOrder(self.birthday, self.left_treatment)
        UserDataDialog.setTabOrder(self.left_treatment, self.left_deafBeforeCI)
        UserDataDialog.setTabOrder(self.left_deafBeforeCI, self.left_deafReason)
        UserDataDialog.setTabOrder(self.left_deafReason, self.left_deafeningProgress)
        UserDataDialog.setTabOrder(self.left_deafeningProgress, self.right_treatment)
        UserDataDialog.setTabOrder(self.right_treatment, self.right_deafBeforeCI)
        UserDataDialog.setTabOrder(self.right_deafBeforeCI, self.right_deafReason)
        UserDataDialog.setTabOrder(self.right_deafReason, self.right_deafeningProgress)
        UserDataDialog.setTabOrder(self.right_deafeningProgress, self.pbSave)
        UserDataDialog.setTabOrder(self.pbSave, self.pbCancel)
        UserDataDialog.setTabOrder(self.pbCancel, self.comment)
        UserDataDialog.setTabOrder(self.comment, self.pbClear)

    def retranslateUi(self, UserDataDialog):
        _translate = QtCore.QCoreApplication.translate
        UserDataDialog.setWindowTitle(_translate("UserDataDialog", "User data"))
        self.lbLastname.setText(_translate("UserDataDialog", "Family name"))
        self.lbForname.setText(_translate("UserDataDialog", "Forname"))
        self.lbPatientID.setText(_translate("UserDataDialog", "Patient-ID"))
        self.lbGender.setText(_translate("UserDataDialog", "Gender"))
        self.gender.setItemText(1, _translate("UserDataDialog", "Female"))
        self.gender.setItemText(2, _translate("UserDataDialog", "Male"))
        self.gender.setItemText(3, _translate("UserDataDialog", "Diverse"))
        self.lbBirthday.setText(_translate("UserDataDialog", "Birthday"))
        self.birthday.setDisplayFormat(_translate("UserDataDialog", "dd.MM.yyyy"))
        self.lbTinnitus.setText(_translate("UserDataDialog", "Tinnitus"))
        self.lbVertigo.setText(_translate("UserDataDialog", "Vertigo"))
        self.left_deafReason.setItemText(1, _translate("UserDataDialog", "Unknown"))
        self.left_deafReason.setItemText(2, _translate("UserDataDialog", "Meningitis"))
        self.left_deafReason.setItemText(3, _translate("UserDataDialog", "Sudden hearing loss"))
        self.left_deafReason.setItemText(4, _translate("UserDataDialog", "Genetical"))
        self.left_deafReason.setItemText(5, _translate("UserDataDialog", "Inner ear inflammation"))
        self.left_deafReason.setItemText(6, _translate("UserDataDialog", "Congenital"))
        self.right_deafReason.setItemText(1, _translate("UserDataDialog", "Unknown"))
        self.right_deafReason.setItemText(2, _translate("UserDataDialog", "Meningitis"))
        self.right_deafReason.setItemText(3, _translate("UserDataDialog", "Sudden hearing loss"))
        self.right_deafReason.setItemText(4, _translate("UserDataDialog", "Genetical"))
        self.right_deafReason.setItemText(5, _translate("UserDataDialog", "Inner ear inflammation"))
        self.right_deafReason.setItemText(6, _translate("UserDataDialog", "Connate"))
        self.lbDeafBeforeCI.setText(_translate("UserDataDialog", "Duration of deafness  before CI Treatment"))
        self.lbDeafeningProgress.setText(_translate("UserDataDialog", "Type of deafness"))
        self.lbDeafReason.setText(_translate("UserDataDialog", "Reason of deafness"))
        self.left_tinnitus.setItemText(1, _translate("UserDataDialog", "Yes"))
        self.left_tinnitus.setItemText(2, _translate("UserDataDialog", "No"))
        self.right_tinnitus.setItemText(1, _translate("UserDataDialog", "Yes"))
        self.right_tinnitus.setItemText(2, _translate("UserDataDialog", "No"))
        self.left_deafBeforeCI.setItemText(1, _translate("UserDataDialog", "< 1 year"))
        self.left_deafBeforeCI.setItemText(2, _translate("UserDataDialog", "1 to 4 years"))
        self.left_deafBeforeCI.setItemText(3, _translate("UserDataDialog", "5 to 10 years"))
        self.left_deafBeforeCI.setItemText(4, _translate("UserDataDialog", "11 to 20 years"))
        self.left_deafBeforeCI.setItemText(5, _translate("UserDataDialog", "21 to 30 years"))
        self.left_deafBeforeCI.setItemText(6, _translate("UserDataDialog", "> 31 years"))
        self.right_deafBeforeCI.setItemText(1, _translate("UserDataDialog", "< 1 year"))
        self.right_deafBeforeCI.setItemText(2, _translate("UserDataDialog", "1 to 4 years"))
        self.right_deafBeforeCI.setItemText(3, _translate("UserDataDialog", "5 to 10 years"))
        self.right_deafBeforeCI.setItemText(4, _translate("UserDataDialog", "11 to 20 years"))
        self.right_deafBeforeCI.setItemText(5, _translate("UserDataDialog", "21 to 30 years"))
        self.right_deafBeforeCI.setItemText(6, _translate("UserDataDialog", "> 31 years"))
        self.left_deafeningProgress.setItemText(1, _translate("UserDataDialog", "Progredient"))
        self.left_deafeningProgress.setItemText(2, _translate("UserDataDialog", "Sudden"))
        self.right_deafeningProgress.setItemText(1, _translate("UserDataDialog", "Progredient"))
        self.right_deafeningProgress.setItemText(2, _translate("UserDataDialog", "Sudden"))
        self.vertigo.setItemText(1, _translate("UserDataDialog", "Yes"))
        self.vertigo.setItemText(2, _translate("UserDataDialog", "No"))
        self.left_treatment.setItemText(1, _translate("UserDataDialog", "Untreated"))
        self.left_treatment.setItemText(2, _translate("UserDataDialog", "Hearing aid"))
        self.left_treatment.setItemText(3, _translate("UserDataDialog", "Cochlear Implant"))
        self.left_treatment.setItemText(4, _translate("UserDataDialog", "Bone conduction hearing aid"))
        self.left_treatment.setItemText(5, _translate("UserDataDialog", "Middle ear implant"))
        self.right_treatment.setItemText(1, _translate("UserDataDialog", "Untreated"))
        self.right_treatment.setItemText(2, _translate("UserDataDialog", "Hearing aid"))
        self.right_treatment.setItemText(3, _translate("UserDataDialog", "Cochlear Implant"))
        self.right_treatment.setItemText(4, _translate("UserDataDialog", "Bone conduction hearing aid"))
        self.right_treatment.setItemText(5, _translate("UserDataDialog", "Middle ear implant"))
        self.lbTreatment.setText(_translate("UserDataDialog", "Treatment"))
        self.lbSubjectId.setText(_translate("UserDataDialog", "Subject ID"))
        self.lbStudyCheck.setText(_translate("UserDataDialog", "General study agreement"))
        self.studyCheck.setText(_translate("UserDataDialog", "Yes"))
        self.lbDifficulty.setText(_translate("UserDataDialog", "<html><head/><body><p>Degree of difficulty </p><p>1 (very easy) - 5 (very hard)</p></body></html>"))
        self.difficulty.setItemText(0, _translate("UserDataDialog", "1"))
        self.difficulty.setItemText(1, _translate("UserDataDialog", "2"))
        self.difficulty.setItemText(2, _translate("UserDataDialog", "3"))
        self.difficulty.setItemText(3, _translate("UserDataDialog", "4"))
        self.difficulty.setItemText(4, _translate("UserDataDialog", "5"))
        self.lbComment.setText(_translate("UserDataDialog", "Comment:"))
        self.pbClear.setText(_translate("UserDataDialog", "Delete"))
        self.pbSave.setText(_translate("UserDataDialog", "Save"))
        self.pbCancel.setText(_translate("UserDataDialog", "Cancel"))
